apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-volume
  labels:
    zone: us-est-coast
    cluster: test-cluster1
    rack: rack-22
  annotations:
    build: two
    builder: john-doe
spec:
  containers:
  - name: test1-container
    image: busybox
    imagePullPolicy: Never
    command: [ "sh", "-c" ]
    args:
    - while true; do
        if [[ -e /etc1/labels ]];then
          echo -en '\n\n'; cat /etc1/labels; fi;
        if [[ -e /etc1/annotations ]];then
          echo -en '\n\n'; cat /etc1/annotations; fi;
        sleep 3600;
      done;
    volumeMounts:
      - name: podinfo
        mountPath: /etc1
        readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef: 
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations