apiVersion: v1
kind: Pod
metadata:
  name: nginx-init
spec:
  initContainers:
  - name: busybox
    image: busybox
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://kubernetes.io
  containers:
  - name: nginx
    image: nginx
    ports: 
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}