apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: busybox
    imagePullPolicy: Never
    args:
    - /bin/sh
    - -c
    - echo ok > /tmp/health; sleep 10; rm -fr /tmp/health; sleep 60
    livenessProbe:
      exec:
        command: 
        - cat
        - /tmp/health
      initialDelaySeconds: 15
      timeoutSeconds: 1